#!/bin/bash

(( EUID )) && SUDO="sudo"

name="$(basename $0)"
version="0.1.1"

deps_packages="feh giblib1 libimlib2"

do_check_deps_packages(){
    if [ "$(grep -i slax /etc/issue)" != "" ]; then
        distro="Slax"
    fi
    [[ ${distro} ]] || distro="$(lsb_release --short --id 2>/dev/null)"
    if [ "$(echo ${distro} | grep -i -e ubuntu -e debian -e mint -e slax)" = "" ]; then
        echo "Right now only Ubuntu, Debian, Mint or Slax is supported for automatic check/install dependency packages..."
        echo "On your distro must manually check/install packages: ${deps_packages}"
        read -n1 -p "Press any key..."
    else
        for package in ${deps_packages}; do
            dpkg -l ${package} &>/dev/null || install_packages="${install_packages} ${package}"
        done
        [[ ${install_packages} ]] && (echo "Installing deps package(s): ${install_packages}"; ${SUDO} apt update -qq && ${SUDO} apt install ${install_packages})
    fi
}

do_test_lcd(){
    backlight_path="/sys/class/backlight/acpi_video0"

    if [ -d ${backlight_path} ]; then
        backlight_old="$(cat ${backlight_path}/brightness)"
        echo "$(cat ${backlight_path}/max_brightness)" >  ${backlight_path}/brightness
    fi

    feh --fullscreen --auto-zoom --hide-pointer --no-menus --preload --quiet --sort filename /usr/local/share/${name}/*.png

    if [ -d ${backlight_path} ]; then
        echo "${backlight_old}" > ${backlight_path}/brightness
    fi
}

do_install(){
    echo "Installing..."
    do_check_deps_packages
    ${SUDO} mkdir -p "/usr/local/share/${name}"
    ${SUDO} cp -a *.png "/usr/local/share/${name}"
    ${SUDO} cp -a "${name}" /usr/local/bin
    echo "Done..."
}

do_uninstall(){
    echo "Uninstalling..."
    ${SUDO} rm -R "/usr/local/share/${name}"
    ${SUDO} rm "/usr/local/bin/${name}"
    echo "Done..."
}

do_help(){
    echo -e "usage: ${name} [OPTION]\n\
-t, --test\t run test lcd (color cycle using space, exit using escape)\n\
-i, --install\t install to /usr/local/{bin,share}\n\
-u, --uninstall\t uninstall from /usr/local"
}

do_version(){
    echo "${name} ${version}"
}

case ${1} in
    '-t'|'--test') do_test_lcd;;
    '-i'|'--install') do_install;;
    '-u'|'--uninstall') do_uninstall;;
    '-v'|'--version') do_version;;
    *) echo "unknown option"; do_help;;
esac
